receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    loglevel: debug 
  otlp:
    endpoint: "http://tempo:4318/v1/traces" 
    tls:
      insecure: true  

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, otlp] 

extensions:
